### ISSUE TITLE
Searching forum

### ISSUE THREAD

**Issue by toteph42** [Kuestenschmiede/ForumBundle#27]
I created a full index and expected search to work...

1. Using external cronjob seams not to index any con4gis-forum.
2. I then created a full index in BE, but Contao "search machine" does not find any forum post (according to search-index-log, the threads-links were made available to search engine).
3. Even worse - I enabled search in con4gis-forum, but  nothing was found (I searched for one word available in 40 posts).

**Comment by coastforge-mei** [comment]
This does not sound good. We'll look into it. The full text search of the forum is many years old. An own technique for mass data. You can retrigger the indexing of the search database in the forum area / forum structure (button above the list). Normally this should happen automatically every time you make changes. We check this.

In the Contao search the forum posts might not appear. This must be upgraded. Unfortunately we do not have enough time for this.

**Comment by coastforge-rro** [comment]
We have been unable to replicate any problems with the search function, but perhaps some clarification is in order. You need to use the forum's in-built search function, Contao's search function won't work, as mei pointed out. The Crawler may crawl the forum thread links, but it won't find anything since the forum is AJAX based.
